const slides=[...document.querySelectorAll('.slide')],index=document.querySelector('#index'),prev=document.querySelector('#prev'),next=document.querySelector('#next'),count=document.querySelector('#count'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let current=0;
slides.forEach(s=>s.hidden=false);
function countUp(el){const final=el.dataset.final||(el.dataset.final=el.textContent);el.textContent=final;const m=final.match(/^([^\d]*)([\d,]+(?:\.\d+)?)(.*)$/);if(reduced.matches||!m||/^Q\d|^Y\d/.test(final)||/\d/.test(m[3]))return;const token=(Number(el.dataset.run)||0)+1;el.dataset.run=token;const target=Number(m[2].replaceAll(',','')),decimals=(m[2].split('.')[1]||'').length,start=performance.now();function tick(now){if(Number(el.dataset.run)!==token)return;const p=Math.min(1,(now-start)/1300);el.textContent=p===1?final:m[1]+(target*(1-(1-p)**3)).toLocaleString('en-AU',{minimumFractionDigits:decimals,maximumFractionDigits:decimals,useGrouping:m[2].includes(',')})+m[3];if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
const observer=new IntersectionObserver(entries=>{entries.forEach(({target,isIntersecting})=>{if(!isIntersecting)return;target.classList.add('in-view');if(target.classList.contains('number'))countUp(target);observer.unobserve(target)})},{threshold:.15,rootMargin:'0px 0px -8% 0px'});
const targets=[...document.querySelectorAll('.reveal,.number,.chart,.stack-diagram,.amount-track')].filter(t=>!t.closest('.enhanced-slide'));targets.forEach(t=>observer.observe(t));
function update(){let n=0;const line=innerHeight*.3;slides.forEach((s,i)=>{if(s.getBoundingClientRect().top<=line)n=i});current=n;index.value=n;count.textContent=`${n+1} / ${slides.length}`;prev.disabled=n===0;next.disabled=n===slides.length-1;history.replaceState(null,'',`#${slides[n].id}`);window.dispatchEvent(new CustomEvent('presentation-active',{detail:slides[n]}))}
let pending=false;window.addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(()=>{update();pending=false})}},{passive:true});
function go(n,smooth=true){slides[Math.max(0,Math.min(slides.length-1,n))].scrollIntoView({behavior:smooth&&!reduced.matches?'smooth':'instant',block:'start'})}prev.onclick=()=>go(current-1);next.onclick=()=>go(current+1);index.onchange=()=>go(Number(index.value));
document.querySelectorAll('[data-slide-target]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();const target=document.getElementById(link.dataset.slideTarget);if(!target)return;history.pushState(null,'','#'+target.id);target.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'})}));
function fromHash(){const n=slides.findIndex(s=>'#'+s.id===location.hash);if(n>=0)go(n,false)}window.addEventListener('hashchange',fromHash);
document.querySelector('#replay').onclick=()=>{if(window.replayPresentation?.(slides[current]))return;slides[current].querySelectorAll('.in-view').forEach(t=>{t.classList.remove('in-view');void t.offsetWidth;observer.observe(t)})};
document.addEventListener('keydown',e=>{if(['SELECT','BUTTON','INPUT'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();go(current+(e.key==='ArrowRight'?1:-1))}});
const full=document.querySelector('#fullscreen');if(!document.fullscreenEnabled)full.hidden=true;full.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{full.textContent='Full screen unavailable'}};document.addEventListener('fullscreenchange',()=>full.textContent=document.fullscreenElement?'Exit full screen':'Full screen');
let zoom=1;const deck=document.querySelector('#deck');function setZoom(v){zoom=Math.max(.75,Math.min(2,v));deck.style.zoom=zoom;window.dispatchEvent(new Event('resize'))}document.querySelector('#plus').onclick=()=>setZoom(zoom+.1);document.querySelector('#minus').onclick=()=>setZoom(zoom-.1);document.querySelector('#fit').onclick=()=>setZoom(1);fromHash();update();
